Paxel/urls.py
from django.contrib import admin
from django.urls import path, include

#vistas
from usuarios import views as usuarios_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/',include(('usuarios.urls','usuarios'),namespace='usuarios')),
    path('',include(('foro.urls','foro'),namespace='inicio')),
]

foro/urls.py
from django.urls import path
#Views
from foro import views

urlpatterns = [
    path(
        #Lista los post
        route = '',
        view = views.ListPostsView.as_view(),
        name = 'index'
    ),
    path(
        #Detalle del post
        route = 'foro/<int:pk>',
        view = views.DetailPostView.as_view(),
        name = 'detailPost'
    ),
    path(
        #Crear un post
        route = 'foro/crear',
        view = views.CreatePostView.as_view(),
        name = 'createPost'
    ),
    path(
        #Actualizar un post
        route = 'foro/edit/<int:pk>',
        view = views.UpdatePostView.as_view(),
        name = 'updatePost'
    ),
    path(
        #Eliminar un post
        route = 'foro/delete/<int:pk>',
        view = views.DeletePostView.as_view(),
        name = 'deletePost'
    ),
    path(
        #Acceso Denegado
        route = 'foro/acceso-no-permitido',
        view = views.DenigedAcces.as_view(),
        name = 'DenigedAcces'
    ),
]

usuarios/urls.py
from django.urls import path
#Views
from usuarios import views

urlpatterns = [
    path(
        route = 'login/', 
        view = views.login_view, 
        name = 'login'
    ),
    path(
        route = 'logout/',
        view = views.logout_view,
        name = 'logout'
    ),
    path(
        route = 'signup/',
        view = views.crear_usuario,
        name = 'crear_usuario',
    ),
    path(
        route = 'update/',
        view = views.act_datos_view,
        name = 'act_datos',
    ),
]

usuarios/models.py
from django.contrib.auth.models import User
from django.db import models

#Todos los datos de los usuarios
class Perfil(models.Model):
    nick = models.OneToOneField(User, on_delete=models.CASCADE)
    creado = models.DateTimeField(auto_now_add=True)
    nacim = models.DateField(blank=True)
    imagen  = models.ImageField(
        upload_to='usuarios/images',
        blank=True,
        null=True
    )
    genero = models.CharField(max_length=15, blank = True)
    num_celular = models.CharField(max_length=10,blank = True)
    pais = models.CharField(max_length = 50)
    biografia = models.TextField(blank=True)
    sentecia = models.TimeField(blank=True,null=True)
    llamados_atencion = models.IntegerField(blank=True,null=True)

#Tabla con los datos de sentencias con usuarios
class BannData(models.Model):
    nick = models.ManyToManyField("usuarios.Perfil")
    id = models.AutoField(primary_key=True)
    contenido_comentario = models.CharField(max_length=250, null=True, blank=True)
    foro_report = models.CharField(max_length=70)
    codigo_foro = models.IntegerField()
    id_comentario = models.OneToOneField("foro.comentarios", on_delete=models.CASCADE)
    causa = models.CharField(max_length=100)
    

usuarios/forms.py
from django import forms
from django.forms.widgets import TextInput
#Modelos
from django.contrib.auth.models import User
from usuarios.models import Perfil

class Crear_Usuario_Form(forms.Form):
    #Formulario para crear usuarios

    username = forms.CharField(
        min_length=6, 
        max_length=20,
        widget=forms.TextInput(
            attrs={
                'placeholder':'Usuario o Nick',
                'class':'form-control',
                'required':True}
        )
    )
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                'placeholder':'Correo elecrónico',
                'class':'form-control',
                'required':True}
        )
    )
    password = forms.CharField(
        min_length=8, 
        max_length=20,
        widget=forms.PasswordInput(
            attrs={
                'placeholder':'Contraseña',
                'class':'form-control',
                'required':True}
        )
    )
    
    password_confirmation = forms.CharField(
        min_length=8, 
        max_length=20,
        widget=forms.PasswordInput(
            attrs={
                'placeholder':'Vuelva a escribir la contraseña',
                'class':'form-control',
                'required':True}
        )
    )
    first_name = forms.CharField(
        min_length=3, 
        max_length=15,
        widget=forms.TextInput(
            attrs={
                'placeholder':'Nombre',
                'class':'form-control',
                'required':True}
        )
    )
    last_name = forms.CharField(
        min_length=3, 
        max_length=15,
        widget=forms.TextInput(
            attrs={
                'placeholder':'Apellido',
                'class':'form-control',
                'required':True}
        )
    )
    pais = forms.CharField(
        min_length=3, 
        max_length=30,
        widget=forms.TextInput(
            attrs={
                'placeholder':'Pais de origen',
                'class':'form-control',
                'required':True}
        )
    )
    nacim = forms.DateField(
        widget=forms.DateInput(
            attrs={
                'placeholder':'DD/MM/AAAA',
                'class':'form-control',
                'required':True}
        )
    )
    
    def clean(self):
        #verifica si las contraseñas son igules
        data=super().clean()
        password = data['password']
        password_confirmation = data['password_confirmation']
        if password != password_confirmation:
            raise forms.ValidationError('Las contraseñas no coinciden')
        return data
    
    def clean_username(self):
        #Revisa si exite una cuenta con el nick
        data=super().clean()
        username = data['username']
        username_en_uso = User.objects.filter(username=username).exists()
        if username_en_uso:
            raise forms.ValidationError('El nombre de usuario ya existe, pruebe con otro')
        return username
    
    def clean_email(self):
        #Revisa si exite una cuenta con este email
        data=super().clean()
        email = data['email']
        email_en_uso = User.objects.filter(email=email).exists()
        if email_en_uso:
            raise forms.ValidationError('Ya existe una cuenta con este email')
        return email

    def save(self):
        #Guardando datos
        data = self.cleaned_data
        #pasando y elminando datos no pertenecientes al modelo User
        data.pop('password_confirmation')
        pais = data['pais']
        data.pop('pais')
        nacim = data['nacim']
        data.pop('nacim')
        user=User.objects.create_user(**data)
        #Guardando en el modelo perfil
        perfil = Perfil(nick=user,pais=pais,nacim=nacim)
        perfil.save()

class Act_Usuario_Form(forms.Form):
    email = forms.EmailField(required=True)
    genero = forms.CharField(min_length=3, max_length=20, required=True)
    first_name = forms.CharField(min_length=3, max_length=15, required=True)
    last_name = forms.CharField(min_length=3, max_length=15, required=True)
    num_celular = forms.IntegerField(required=False)
    biografia = forms.CharField(max_length=500, required=False)

    def clean_email(self):
        #Revisa si exite una cuenta con este email
        data=super().clean()
        email = data['email']
        email_en_uso = User.objects.filter(email=email).exists()
        if email_en_uso:
            raise forms.ValidationError('Ya existe una cuenta con este email')
        return email

    def save(self):
        #Guardando datos
        data = self.cleaned_data
        #Asignanado datos por variable
        email = data['email']
        genero = data['genero']
        first_name = data['first_name']
        last_name = data['last_name']
        num_celular = data['num_celular']
        biografia = data['biografia']
        #Guardando en el modelo Users
        user = User(first_name=first_name, last_name=last_name)
        user.save()
        perfil = Perfil(email=email, genero=genero, num_celular=num_celular, biografia=biografia)

usuarios/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse

#Modelos
from django.contrib.auth.models import User
from usuarios.models import Perfil

#Formularios
from usuarios.forms import Crear_Usuario_Form
from usuarios.forms import Act_Usuario_Form

def login_view(request):
    #Sistema de login
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect('foro:index')
        else:
            return render(request, 'usuarios/login.html',{'error':'Usuario o contraseña erroneos'})
    return render(request,'usuarios/login.html')

def logout_view(request):
    logout(request)
    return redirect('usuarios:login')

def crear_usuario(request):
    if request.method == 'POST':
        form = Crear_Usuario_Form(request.POST)
        if form.is_valid():
            form.save()
            return redirect('foro:index')
    else:
        form = Crear_Usuario_Form()
    return render(
        request=request,
        template_name='usuarios/crear_usuarios.html',
        context={
            'form':form,
            }
    )

@login_required
def act_datos_view(request):
    #Actualizar datos del usuario
    if request.method == 'POST':
        form = Act_Usuario_Form(request.POST)
        if form.is_valid():
            form.save()
            return redirect('foro:index')
    else:
        form = Act_Usuario_Form()
    return render(
        request=request,
        template_name='usuarios/actualizar_datos.html',
        context={
            'form':form,
            'user':request.user,
            'perfil':Perfil
        }
    )

templates/usuarios/actualizar_datos.html
{% extends 'base.html' %}

{% block head_contenido %}
<title>Paxel | Actualizar datos</title>
{% endblock %}

{% block container %}
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-5 offset-md-4 text-center">
                <h1 class="display-2">Actualiza tus datos personales</h1>
            </div>
        </div>
    </div>

    {# Nick #}

        <div class="container">
            <div class="row">
                <div class="col-12 col-md-8 offset-md-2 text-center">
                    <h1 class="display-4">Bienvenido @{{ user.username }}</h1>
                </div>
            </div>
        </div>

    {# Formulario #}
    
    <form action="{% url 'usuarios:act_datos' %}" method="POST">
        {% csrf_token %}
        <div class="container">
            <div class="row mb-3">
                {# Email #}
                <div class="col-12 col-md-5 offset-md-1">
                    <div class="input-group">
                        <span class="input-group-text">Correo</span>
                        <input 
                            class="form-control" 
                            type="text" 
                            name="email"
                            placeholder="Email"
                            value="{% if form.errors %}{{ form.email.value }}{% else %}{{ user.email }}{% endif %}"
                        >
                    </div>
                </div>
                {# Genero #}
                <div class="col-12 col-md-5">
                    <div class="input-group">
                        <label class="input-group-text" for="generochoose">Genero</label>
                        <select class="form-select" name="genero" id="generochoose">
                            <option selected>{% if perfil.genero.value %}{{ form.genero.value }}{% else %}Seleccione una opción{% endif %}</option>
                            <option value="hombre">Hombre</option>
                            <option value="mujer">Mujer</option>
                            <option value="otro">Otro</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="row mb-3">
                {# Nombre completo #}
                <div class="col-12 col-md-10 offset-md-1">
                    
                    <div class="input-group">
                        <span class="input-group-text">Nombre y apellido</span>
                        <input 
                            class="form-control" 
                            type="text" 
                            name="first_name"
                            placeholder="Primer nombre"
                            value="{% if form.errors %}{{ form.first_name.value }}{% else %}{{ user.first_name }}{% endif %}"
                        >
                        <input 
                            class="form-control" 
                            type="text" 
                            name="last_name"
                            placeholder="Segundo nombre"
                            value="{% if form.errors %}{{ form.last_name.value }}{% else %}{{ user.last_name }}{% endif %}"
                        >
                    </div>
                </div>
                
            </div>
            <div class="row mb-3">
                {# Numero de telefono #}
                <div class="col-12 col-md-4 offset-md-1">
                    <div class="input-group">
                        <span class="input-group-text">Numero de telefono</span>
                        <input 
                            class="form-control" 
                            type="text" 
                            name="num_celular"
                            placeholder="Numero de telefono"
                            value="{% if form.errors %}{{ form.num_celular.value }}{% else %}{{ perfil.num_celular }}{% endif %}"
                        >
                    </div>
                </div>
            </div>
            <div class="row">
                    {# Biografia #}
                    <div class="col-12 col-md-10 offset-md-1 mt-3">
                        <h4>Biografia</h4>
                        <textarea 
                            class="form-control {% if form.biografia.errors %}is-invalid{% endif %}"
                            name="biografia" 
                        >
                        {% if form.errors %}{{ form.biografia.value }}{% else %}{{ perfil.biografia }}{% endif %}
                        </textarea>
                    </div>
            </div>
            <div class="row">
                <div class="col-12 col-md-9 offset-md-1">
                    <h1 class="display-4">Datos </h1>
                </div>
            </div>
            <div class="row">
                <div class="d-grid gap-2 col-12 col-md-3 mx-auto">
                    <button class="btn btn-primary btn-block mt-5" type="submit">Actualizar</button>
                </div>
            </div>
        </div>
        
        
        <div class="container">
                <div class="row">
                    <div class="col-12 col-md-9 offset-md-1">
                        <h1>Cambiar contraseña </h1>
                        <button class="btn btn-primary btn-block mt-5">Click aqui para cambiar la contraseña</button>
                    </div>
                </div>
            </div>
    </form>
{% endblock %}

templates/usuarios/crear_usuarios.html
{% extends 'base.html' %}
{% block head_contenido %}
<title>Paxel | Crear usuario</title>
{% endblock %}

{% block container %}
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-5 offset-md-4 text-center">
                <h1 class="display-2">Registrate</h1>
            </div>
        </div>

    </div>
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6 offset-md-3">
                <form action="{% url 'usuarios:crear_usuario' %}" method="POST">
                    {% csrf_token %}
                    
                    {{ form.as_p }}
            
                    <button class="btn btn-primary btn-block mt-5" type="submit">Registrar</button>
                </form>

            </div>
        </div>
    </div>
    
{% endblock %}

templates/usuarios/login.html
{% extends 'base.html' %}
{% block head_contenido %}
<title>Paxel | Login</title>
{% endblock %}
{% block container %}
<div class="container">
  <div class="row">
    <div class="col-md-4 offset-md-4 mt-4">
      <h2 class="display-5 text-center">Bienvenido a Paxel</h2>
      <p class="text-center">Los foros para los Gays, para los Gamers </p>
      {% if error %}
        <p class="alert alert-danger">{{ error }}</p>
      {% endif %}
      {% if nota %}
        <p class="alert alert.succes" role="alert">{{ nota }}</p>
      {% endif %}
      <form method="POST" actions="{% url 'usuarios:login' %}">
        {% csrf_token %}
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Nick o correo electronico</label>
          <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="username">
          <div id="emailHelp" class="form-text">Nick: Alejandro1234 - Correo: ejemplo@ejemplo.com </div>
        </div>
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">Contraseña</label>
          <input type="password" class="form-control" id="exampleInputPassword1" name="password">
        </div>
        <div class="mb-3 form-check">
          <input type="checkbox" class="form-check-input" id="exampleCheck1">
          <label class="form-check-label" for="exampleCheck1">Recuerdame</label>
        </div>
        <button type="submit" class="btn btn-primary">Entrar</button>
        <p>No estas registrado? <a href="{% url 'usuarios:crear_usuario' %}">Registrate aqui</a></p>
      </form>
    </div>
  </div>
</div>

{% endblock %}