Paxel/urls.py
from django.contrib import admin
from django.urls import path, include

#vistas
from usuarios import views as usuarios_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/',include(('usuarios.urls','usuarios'),namespace='usuarios')),
    path('',include(('foro.urls','foro'),namespace='inicio')),
]

foro/urls.py
from django.urls import path
#Views
from foro import views

urlpatterns = [
    path(
        #Lista los post
        route = '',
        view = views.ListPostsView.as_view(),
        name = 'index'
    ),
    path(
        #Detalle del post
        route = 'foro/<int:pk>',
        view = views.DetailPostView.as_view(),
        name = 'detailPost'
    ),
    path(
        #Crear un post
        route = 'foro/crear',
        view = views.CreatePostView.as_view(),
        name = 'createPost'
    ),
    path(
        #Actualizar un post
        route = 'foro/edit/<int:pk>',
        view = views.UpdatePostView.as_view(),
        name = 'updatePost'
    ),
    path(
        #Eliminar un post
        route = 'foro/delete/<int:pk>',
        view = views.DeletePostView.as_view(),
        name = 'deletePost'
    ),
    path(
        #Acceso Denegado
        route = 'foro/acceso-no-permitido',
        view = views.DenigedAcces.as_view(),
        name = 'DenigedAcces'
    ),
]

usuarios/urls.py
from django.urls import path
#Views
from usuarios import views

urlpatterns = [
    path(
        route = 'login/', 
        view = views.login_view, 
        name = 'login'
    ),
    path(
        route = 'logout/',
        view = views.logout_view,
        name = 'logout'
    ),
    path(
        route = 'signup/',
        view = views.crear_usuario,
        name = 'crear_usuario',
    ),
    path(
        route = 'update/',
        view = views.act_datos_view,
        name = 'act_datos',
    ),
]

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    {% block head_contenido %}

    {% endblock %}
</head>
<body>
    {% include 'nav.html' %}
    {% block container %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</body>
</html>

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="{% static 'img/logotipo.png' %}" alt="" width="30" height="24" class="d-inline-block align-top">
            Paxel
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav me-auto mb-0 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'foro:index' %}">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Mis foros</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'foro:createPost' %}">Crear foro</a>
                </li>
            </ul>
            <form class="d-flex">
                <input class="form-control" type="search" placeholder="Buscar foro" aria-label="Search">
                <div class="col-5">
                    <button class="btn btn-outline-success" type="submit">Buscar foro</button>
                </div>

            </form>
            <li class="nav-item dropdown">
                <div class="btn-group">

                        {% if request.user.is_authenticated %}
                            <a class="btn btn-danger">
                            {{ request.user.username }}
                        {% else %}
                            <a class="btn btn-danger" href="{% url 'usuarios:login' %}">
                            Iniciar sesion
                        {% endif %}
                    </a>
                    <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
                        <span class="visually-hidden">Toggle Dropdown</span>
                    </button>
                    <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-end" aria-labelledby="navbarDropdown">
                        {% if request.user.is_authenticated %}
                            <li><a class="dropdown-item" href="{% url 'foro:createPost' %}">Crear foro</a></li>
                            <li><a class="dropdown-item" href="#">Administrar foros</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'usuarios:act_datos' %}">Modificar perfil</a></li>
                            <li><a class="dropdown-item" href="{% url 'usuarios:logout' %}">Cerrar sesion</a></li>
                        {% else %}
                            <li><a class="dropdown-item" href="{% url 'usuarios:login' %}">Iniciar sesion</a></li>
                        {% endif %}
                    </ul>
                </div>

            </li>
        </div>
    </div>
</nav>